openapi: 3.0.0

info:
  title: API de ejemplo
  description: Ejemplo de documentación de API
  version: 1.0.0

paths:
  /:
    get:
      summary: Devolver saludo
      responses:
        '200':
          description: Respuesta de saludo
          content:
            application/json:
              schema:
                type: string
                example: ¡Hola Mundo!